import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/index">Index</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/news">News</Link>
        </li>
        <li>
          <Link to="/news1">News1</Link>
        </li>
        <li>
          <Link to="/tenants">Tenants</Link>
        </li>
        <li>
          <Link to="/tenants1">Tenants1</Link>
        </li>
        <li>
          <Link to="/rents">Rents</Link>
        </li>
        <li>
          <Link to="/rents2">Rents2</Link>
        </li>
        <li>
          <Link to="/service">Service</Link>
        </li>
        <li>
          <Link to="/infrastructure">Infrastructure</Link>
        </li>
        <li>
          <Link to="/infrastructure1">Infrastructure1</Link>
        </li>
        <li>
          <Link to="/parking">Parking</Link>
        </li>
        <li>
          <Link to="/contacts">Contacts</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
